language : python
python :
  - 3.7.0

install :
  - pip install -r requirements.txt
  - pip install coveralls

requirements:
  - pytest --cov =api tests/
  - python app.py=api tests/
  
  after_success:
    -coveralls